# Cargo.toml

[package]
name = "bare-metal"         # or any other name
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"

[dependencies]
# # used for UEFI booting in QEMU
# ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = ["kernel"]