[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader_api = "0.11"
x86_64 = { version = "0.14.7", default-features = false, features = [
    "instructions",
    "inline_asm",
] }
uart_16550 = "0.3.0"